version: '3'

services:
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"

  database_seed:
    image: mongo
    links:
      - database
    volumes:
      - ./__tests__/mongo/:/root
    command:
      mongorestore --host database --db ecg-myr /root/
  
  mongoexpress:
    links:
      - database
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    ports:
      - "8081:8081"

  API:
    image: node
    links:
      - database
    volumes:
      - .:/app
    ports:
      - "1337:1337"
    environment: 
      MONGO_CONNECTION_STRING: 'mongodb://database:27017/ecg-myr'
    working_dir: /app
    command: npm start