version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/mern-starter # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.9
      - image: mongo:3.6.7-stretch
    steps: # a collection of executable commands 
      - checkout # special step to check out source code to working directory
      - run:
          name: install-mongo-cli
          command: 'sudo apt-get install mongodb-clients'
      - run:
          name: mongo-test-db
          command: 'mongorestore -d ecg-myr __tests__/mongo'
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
    #   - run: # run server
    #       name: Start server
    #       command: npm start
    #       background: true
    #   - run: # wait for server to start
    #       name: making sure server had time to start
    #       command: sleep 15
      - run: # run tests
          name: test
          command: CI=true npm test
    #   - run: # run coverage report
    #       name: code-coverage
    #       command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts: # special step to save test results as as artifact
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results: # special step to upload test results for display in Test Summary
      #     path: test-results.xml
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    
